#!/usr/bin/env bash
# Start the BTX daemon with the proper data directory.
#
# Creates ~/.btx/btx.conf on first run with a freshly generated random RPC password.
# Subsequent runs reuse the existing config.
#
# After starting, the chain will sync from genesis on first run. This takes
# 4-8 hours depending on bandwidth and CPU. The daemon is non-interactive
# once started; you can close this terminal and it keeps running.

set -euo pipefail

DATADIR="${HOME}/.btx"
BTXD="${HOME}/dev/btx/build/bin/btxd"
BTX_CLI="${HOME}/dev/btx/build/bin/btx-cli"

if [[ ! -x "$BTXD" ]]; then
    echo "❌ btxd not found at $BTXD" >&2
    echo "   Run ./install.sh first." >&2
    exit 1
fi

mkdir -p "$DATADIR"
chmod 700 "$DATADIR"

# Generate fresh ~/.btx/btx.conf on first run with random RPC password
if [[ ! -f "$DATADIR/btx.conf" ]]; then
    echo "Generating fresh ~/.btx/btx.conf (random RPC password)..."
    RPC_PW=$(openssl rand -hex 32)
    cat > "$DATADIR/btx.conf" <<EOF
# BTX node configuration — generated by btx-air-m2-miner on $(date)
# Random RPC password (64 hex chars); RPC bound to localhost only.

server=1
listen=1

# Mainnet ports
port=19335
rpcport=19334

# RPC binding — LOCALHOST ONLY (never expose RPC to the internet)
rpcbind=127.0.0.1
rpcallowip=127.0.0.1
rpcuser=btxrpc
rpcpassword=${RPC_PW}

# Resource budgets — modest defaults that work on 8 GB RAM
dbcache=2048
prune=4096
retainshieldedcommitmentindex=1

# Peer discovery + initial seed nodes (from the BTX project docs)
dnsseed=1
fixedseeds=1
addnode=node.btx.tools:19335
addnode=146.190.179.86:19335
addnode=164.90.246.229:19335
EOF
    chmod 600 "$DATADIR/btx.conf"
    echo "  ✓ Wrote $DATADIR/btx.conf (mode 0600)"
fi

# Already running?
if pgrep -f "btxd.*-datadir=$DATADIR" >/dev/null; then
    echo "✓ btxd is already running (PID $(pgrep -f "btxd.*-datadir=$DATADIR"))"
    "$BTX_CLI" -datadir="$DATADIR" getblockchaininfo 2>&1 | python3 -c "
import sys, json
try:
    d = json.load(sys.stdin)
    print(f'  blocks={d[\"blocks\"]:,}  headers={d[\"headers\"]:,}  progress={d[\"verificationprogress\"]:.4f}  ibd={d[\"initialblockdownload\"]}')
except: pass
"
    exit 0
fi

# Start
echo "Starting btxd as daemon..."
"$BTXD" -daemon -datadir="$DATADIR"
sleep 5

if pgrep -f "btxd.*-datadir=$DATADIR" >/dev/null; then
    echo "  ✓ Started (PID $(pgrep -f "btxd.*-datadir=$DATADIR"))"
else
    echo "  ✗ Failed to start. Check $DATADIR/debug.log"
    tail -20 "$DATADIR/debug.log" 2>/dev/null || true
    exit 1
fi

echo
echo "Chain sync starts now. First full sync is 4-8 hours."
echo "Check progress anytime with:"
echo "  $BTX_CLI -datadir=$DATADIR getblockchaininfo"
echo
echo "When 'initialblockdownload' goes false and 'verificationprogress' ≥ 0.999,"
echo "you're synced and ready to mine."
