#!/usr/bin/env bash
# Run the mining loop. Takes your P2MR payout address as the only argument.
#
# Usage:
#   ./scripts/start-mining.sh <btx1z-address>
#
# Runs in the background via nohup. Logs to ~/.btx/mining-loop.log.
# Stop with ./scripts/stop-mining.sh.
#
# The dashboard (./dashboard/start.sh) reads this log to display live stats.

set -euo pipefail

PAYOUT="${1:-}"
DATADIR="${HOME}/.btx"
BTX_CLI="${HOME}/dev/btx/build/bin/btx-cli"

if [[ -z "$PAYOUT" ]]; then
    cat <<EOF
Usage: $0 <btx1z-payout-address>

  Pass the BTX address generated by ./scripts/wallet-setup.sh.
  It must start with 'btx1z' (P2MR / post-quantum format).

  Example:
    $0 btx1zabc...xyz

EOF
    exit 1
fi

if [[ ! "$PAYOUT" =~ ^btx1z[a-z0-9]+$ ]]; then
    echo "❌ Address doesn't look like a P2MR address. Must start with 'btx1z'." >&2
    exit 1
fi

if [[ ! -x "$BTX_CLI" ]]; then
    echo "❌ btx-cli not found. Run ./install.sh first." >&2
    exit 1
fi

if ! pgrep -f "btxd.*-datadir=$DATADIR" >/dev/null; then
    echo "❌ btxd not running. Run ./scripts/start-daemon.sh first." >&2
    exit 1
fi

# Check sync status
SYNCED=$("$BTX_CLI" -datadir="$DATADIR" getblockchaininfo | python3 -c 'import sys,json;d=json.load(sys.stdin);print("yes" if d["verificationprogress"] > 0.99 and not d["initialblockdownload"] else "no")')
if [[ "$SYNCED" != "yes" ]]; then
    echo "⏳ Chain not fully synced yet. You CAN mine before full sync, but you'll mine on stale state."
    PROG=$("$BTX_CLI" -datadir="$DATADIR" getblockchaininfo | python3 -c 'import sys,json;d=json.load(sys.stdin);print(f"{d[\"verificationprogress\"]*100:.1f}%")')
    read -rp "    Current sync: $PROG. Start mining anyway? [yes/no]: " GO
    [[ "$GO" == "yes" ]] || exit 0
fi

# Already running?
if [[ -f "$DATADIR/mining-loop.pid" ]]; then
    OLD_PID=$(cat "$DATADIR/mining-loop.pid")
    if kill -0 "$OLD_PID" 2>/dev/null; then
        echo "✓ Mining loop is already running (PID $OLD_PID)."
        echo "  Stop it first with ./scripts/stop-mining.sh"
        exit 0
    fi
fi

# Launch the mining loop in the background
nohup bash -c "
PAYOUT='$PAYOUT'
DATADIR='$DATADIR'
BTX_CLI='$BTX_CLI'
LOG='$DATADIR/mining-loop.log'
PIDFILE='$DATADIR/mining-loop.pid'
MAXTRIES=1000000

echo \$\$ > \"\$PIDFILE\"
echo \"[\$(date '+%Y-%m-%d %H:%M:%S')] Mining loop started, PID=\$\$, payout=\$PAYOUT, maxtries=\$MAXTRIES\" >> \"\$LOG\"

ITER=0
BLOCKS_FOUND=0
TOTAL_TRIES=0
START_T=\$(date +%s)

trap 'echo \"[\$(date +%H:%M:%S)] received signal, exiting after iter \$ITER\" >> \"\$LOG\"; rm -f \"\$PIDFILE\"; exit 0' SIGTERM SIGINT

while true; do
    ITER=\$((ITER+1))
    RESULT=\$(\"\$BTX_CLI\" \"-datadir=\$DATADIR\" \"-rpcwallet=miner\" generatetoaddress 1 \"\$PAYOUT\" \"\$MAXTRIES\" 2>&1)
    NOW=\$(date +%s)
    TOTAL_TRIES=\$((TOTAL_TRIES+MAXTRIES))

    if echo \"\$RESULT\" | grep -q '\"' ; then
        BLOCKS_FOUND=\$((BLOCKS_FOUND+1))
        BLOCKHASH=\$(echo \"\$RESULT\" | grep -oE '\"[a-f0-9]{64}\"' | head -1)
        echo \"[\$(date '+%H:%M:%S')] iter \$ITER: ⭐ BLOCK FOUND! hash=\$BLOCKHASH\" >> \"\$LOG\"
    else
        if [ \$((ITER % 10)) -eq 0 ]; then
            ELAPSED=\$((NOW-START_T))
            RATE=\$((TOTAL_TRIES/ELAPSED))
            echo \"[\$(date '+%H:%M:%S')] iter \$ITER: tries=\$TOTAL_TRIES blocks=\$BLOCKS_FOUND elapsed=\${ELAPSED}s rate=\${RATE}/s\" >> \"\$LOG\"
        fi
    fi
done
" >/dev/null 2>&1 &

MINER_PID=$!
echo "$MINER_PID" > "$DATADIR/mining-loop.pid"
sleep 2

if kill -0 "$MINER_PID" 2>/dev/null; then
    cat <<EOF

✓ Mining loop started (PID $MINER_PID)
  Payout: $PAYOUT
  Log:    $DATADIR/mining-loop.log

Tail live progress with:
  tail -f $DATADIR/mining-loop.log

Stop with:
  ./scripts/stop-mining.sh

Launch the dashboard in another terminal:
  ./dashboard/start.sh

Note: at base M2 hashrate (~1,000 nonces/sec) and current network conditions,
expect ~1 block per 24 hours on average. See docs/expectations.md for the math.

EOF
else
    echo "✗ Mining loop failed to start. Check the daemon is healthy."
    exit 1
fi
